#require 'spec_helper'
#
## This spec was generated by rspec-rails when you ran the scaffold generator.
## It demonstrates how one might use RSpec to specify the controller code that
## was generated by Rails when you ran the scaffold generator.
##
## It assumes that the implementation code is generated by the rails scaffold
## generator.  If you are using any extension libraries to generate different
## controller code, this generated spec may or may not pass.
##
## It only uses APIs available in rails and/or rspec-rails.  There are a number
## of tools you can use to make these specs even more expressive, but we're
## sticking to rails and rspec-rails APIs to keep things simple and stable.
##
## Compared to earlier versions of this generator, there is very limited use of
## stubs and message expectations in this spec.  Stubs are only used when there
## is no simpler way to get a handle on the object needed for the example.
## Message expectations are only used when there is no simpler way to specify
## that an instance is receiving a specific message.
#
#describe IntervalsController do
#
#  # This should return the minimal set of attributes required to create a valid
#  # Interval. As you add validations to Interval, be sure to
#  # update the return value of this method accordingly.
#  def valid_attributes
#    {}
#  end
#
#  describe "GET index" do
#    it "assigns all intervals as @intervals" do
#      interval = Interval.create! valid_attributes
#      get :index
#      assigns(:intervals).should eq([interval])
#    end
#  end
#
#  describe "GET show" do
#    it "assigns the requested interval as @interval" do
#      interval = Interval.create! valid_attributes
#      get :show, :id => interval.id.to_s
#      assigns(:interval).should eq(interval)
#    end
#  end
#
#  describe "GET new" do
#    it "assigns a new interval as @interval" do
#      get :new
#      assigns(:interval).should be_a_new(Interval)
#    end
#  end
#
#  describe "GET edit" do
#    it "assigns the requested interval as @interval" do
#      interval = Interval.create! valid_attributes
#      get :edit, :id => interval.id.to_s
#      assigns(:interval).should eq(interval)
#    end
#  end
#
#  describe "POST create" do
#    describe "with valid params" do
#      it "creates a new Interval" do
#        expect {
#          post :create, :interval => valid_attributes
#        }.to change(Interval, :count).by(1)
#      end
#
#      it "assigns a newly created interval as @interval" do
#        post :create, :interval => valid_attributes
#        assigns(:interval).should be_a(Interval)
#        assigns(:interval).should be_persisted
#      end
#
#      it "redirects to the created interval" do
#        post :create, :interval => valid_attributes
#        response.should redirect_to(Interval.last)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns a newly created but unsaved interval as @interval" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        Interval.any_instance.stub(:save).and_return(false)
#        post :create, :interval => {}
#        assigns(:interval).should be_a_new(Interval)
#      end
#
#      it "re-renders the 'new' template" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        Interval.any_instance.stub(:save).and_return(false)
#        post :create, :interval => {}
#        response.should render_template("new")
#      end
#    end
#  end
#
#  describe "PUT update" do
#    describe "with valid params" do
#      it "updates the requested interval" do
#        interval = Interval.create! valid_attributes
#        # Assuming there are no other intervals in the database, this
#        # specifies that the Interval created on the previous line
#        # receives the :update_attributes message with whatever params are
#        # submitted in the request.
#        Interval.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
#        put :update, :id => interval.id, :interval => {'these' => 'params'}
#      end
#
#      it "assigns the requested interval as @interval" do
#        interval = Interval.create! valid_attributes
#        put :update, :id => interval.id, :interval => valid_attributes
#        assigns(:interval).should eq(interval)
#      end
#
#      it "redirects to the interval" do
#        interval = Interval.create! valid_attributes
#        put :update, :id => interval.id, :interval => valid_attributes
#        response.should redirect_to(interval)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns the interval as @interval" do
#        interval = Interval.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        Interval.any_instance.stub(:save).and_return(false)
#        put :update, :id => interval.id.to_s, :interval => {}
#        assigns(:interval).should eq(interval)
#      end
#
#      it "re-renders the 'edit' template" do
#        interval = Interval.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        Interval.any_instance.stub(:save).and_return(false)
#        put :update, :id => interval.id.to_s, :interval => {}
#        response.should render_template("edit")
#      end
#    end
#  end
#
#  describe "DELETE destroy" do
#    it "destroys the requested interval" do
#      interval = Interval.create! valid_attributes
#      expect {
#        delete :destroy, :id => interval.id.to_s
#      }.to change(Interval, :count).by(-1)
#    end
#
#    it "redirects to the intervals list" do
#      interval = Interval.create! valid_attributes
#      delete :destroy, :id => interval.id.to_s
#      response.should redirect_to(intervals_url)
#    end
#  end
#
#end
